# -*- coding: utf-8 -*-
"""AI_Chain_Accessory_Try_On.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U_PUadwqYnGBGOQmHL77BnvTj2OyUL__

# AI Necklace / Chain Try-On - Gradio Notebook

This notebook runs the **Gradio UI inside Colab**.

### Features
- **Girl styling** - necklace options
- **Boy styling** - dog tag pendant / chain options
- Uses **OpenAI Image API** for editing
- Loads `OPENAI_API_KEY` from **Colab Secrets**
- No summary or JSON output

### Before running
1. Open the **Secrets** panel in Colab using the key icon on the left.
2. Add a secret named `OPENAI_API_KEY`.
3. Enable notebook access for that secret.
4. Run all cells in order.

Use a clear upper-body photo with one person and a visible neck/chest area.

## 1. Install dependencies
"""

!pip install -q --upgrade openai gradio pillow

"""## 2. Configure OpenAI API key from Colab Secrets"""

import os
from google.colab import userdata

try:
    OPENAI_API_KEY = userdata.get("OPENAI_API_KEY")
except Exception as exc:
    raise RuntimeError(
        "Could not read OPENAI_API_KEY from Colab Secrets. "
        "Add it in the Secrets panel and enable notebook access."
    ) from exc

if not OPENAI_API_KEY:
    raise ValueError(
        "OPENAI_API_KEY is missing. Add it in Colab Secrets and enable notebook access."
    )

os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY
print("OpenAI API key loaded from Colab Secrets.")

"""## 3. Build the Gradio app"""

import os
import io
import base64
import tempfile
from pathlib import Path

import gradio as gr
import openai
from openai import OpenAI
from PIL import Image, ImageOps

IMAGE_MODEL = "gpt-image-2"
OUTPUT_QUALITY = "medium"
OUTPUT_SIZE = "auto"

ACCESSORY_MAP = {
    "Minimal silver necklace": "one delicate minimal silver necklace with a small understated pendant",
    "Delicate gold necklace": "one delicate fine gold necklace with a small elegant pendant",
    "Pearl necklace": "one refined single-strand pearl necklace with realistic natural pearls",
    "Statement necklace": "one tasteful modern statement necklace, elegant rather than oversized",
    "Silver dog tag pendant": (
        "one simple brushed-silver dog tag pendant on a medium-length silver chain, "
        "with no text, logo, military insignia, or engraving"
    ),
    "Minimal silver chain": "one clean minimal silver chain with a subtle medium-width link design",
    "Minimal gold chain": "one clean minimal gold chain with a subtle medium-width link design",
    "Black cord pendant": "one minimal matte-black cord necklace with a small plain dark pendant",
    "Double layered chains": "Add two layered silver chains around the neck, one slightly shorter and one slightly longer, with a clean masculine styling. Keep them realistic and not oversized.",
    "Chain + dog tag pendant": "Add one minimal silver chain together with one slightly longer silver dog tag pendant chain. The layers should sit naturally without tangling."
}


def get_client() -> OpenAI:
    api_key = os.getenv("OPENAI_API_KEY", "").strip()
    if not api_key:
        raise gr.Error(
            "OPENAI_API_KEY is missing. Add it in Colab Secrets before launching the app."
        )
    return OpenAI(api_key=api_key)


def normalize_image(image: Image.Image) -> Image.Image:
    if image is None:
        raise gr.Error("Please upload an image.")

    image = ImageOps.exif_transpose(image)
    image.load()
    image = image.convert("RGB")

    if min(image.size) < 256:
        raise gr.Error(
            f"Image is too small ({image.width}×{image.height}). "
            "Use an image with both dimensions at least 256 px."
        )

    return image


def build_edit_prompt(accessory_description: str) -> str:
    return f'''
Perform a precise photorealistic edit of the supplied photograph.

ONLY EDIT:
Add exactly {accessory_description} around the person's visible neck.

PLACEMENT:
- Position it naturally around the neck and over the existing clothing.
- Match neck angle, body pose, perspective, scale, lighting, shadows,
  highlights, reflections, depth, and occlusion.
- Mix two three chain to give dapper look.
- If Single Chain, then it should be thick and visible.
- If multiple Chain then it should be mix of thin and thick chains.
- Make it look physically worn, not pasted on.

IDENTITY LOCK — DO NOT CHANGE:
- face shape, eyes, eyebrows, nose, lips, teeth, ears, jawline
- skin texture, skin tone, facial expression, gaze direction
- hairstyle, hairline, makeup, age or apparent age
- body shape, body proportions, pose, hands
- clothing, clothing colour, texture, print, fit, or neckline
- background, lighting, camera angle, crop, and composition

STRICT RULES:
- Do not retouch, beautify, smooth, reshape, recolour, or regenerate the face.
- Do not add a second accessory.
- Do not add earrings, glasses, hats, bracelets, watches, rings, or bags.
- Do not add text, logos, symbols, engraving, watermarks, or brand marks.
- Do not remove or redesign anything already present.
- Preserve all pixels outside the neck and upper-chest area as closely as possible.

The final result must look like the same original photograph with only the selected
neck accessory added.
'''.strip()


def generate_try_on(
    image: Image.Image,
    style_mode: str,
    girl_accessory: str,
    boy_accessory: str,
):
    normalized = normalize_image(image)

    selected_accessory = (
        girl_accessory if style_mode == "Girl styling" else boy_accessory
    )
    accessory_description = ACCESSORY_MAP[selected_accessory]
    prompt = build_edit_prompt(accessory_description)

    client = get_client()

    with tempfile.TemporaryDirectory() as tmpdir:
        input_path = Path(tmpdir) / "input.png"
        normalized.save(input_path, format="PNG")

        try:
            with open(input_path, "rb") as image_file:
                response = client.images.edit(
                    model=IMAGE_MODEL,
                    image=image_file,
                    prompt=prompt,
                    quality=OUTPUT_QUALITY,
                    size=OUTPUT_SIZE,
                    output_format="png",
                )
        except openai.AuthenticationError as exc:
            raise gr.Error("Authentication failed. Check OPENAI_API_KEY.") from exc
        except openai.RateLimitError as exc:
            raise gr.Error(
                "The API rate or usage limit was reached. Check billing and limits."
            ) from exc
        except openai.BadRequestError as exc:
            raise gr.Error(f"The image-edit request was rejected: {exc}") from exc
        except openai.APIError as exc:
            raise gr.Error(f"OpenAI image editing failed: {exc}") from exc
        except Exception as exc:
            raise gr.Error(f"Unexpected error: {exc}") from exc

    if not response.data or not response.data[0].b64_json:
        raise gr.Error("The image API returned no image data.")

    image_bytes = base64.b64decode(response.data[0].b64_json)
    output_image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    return output_image


def toggle_accessory_dropdowns(style_mode: str):
    if style_mode == "Girl styling":
        return gr.update(visible=True), gr.update(visible=False)
    return gr.update(visible=False), gr.update(visible=True)


with gr.Blocks(title="AI Necklace / Chain Try-On") as demo:
    gr.Markdown(
        '''
# AI Necklace / Chain Try-On

Upload a clear upper-body photo with one main person and a visible neck/chest area.

- **Girl styling** → necklace options
- **Boy styling** → dog tag pendant or chain options
        '''
    )

    with gr.Row():
        with gr.Column():
            input_image = gr.Image(type="pil", label="Upload Photo")
            style_mode = gr.Radio(
                choices=["Girl styling", "Boy styling"],
                value="Girl styling",
                label="Style mode",
            )
            girl_accessory = gr.Dropdown(
                choices=[
                    "Minimal silver necklace",
                    "Delicate gold necklace",
                    "Pearl necklace",
                    "Statement necklace",
                ],
                value="Minimal silver necklace",
                label="Girl accessory",
                visible=True,
            )
            boy_accessory = gr.Dropdown(
                choices=[
                    "Silver dog tag pendant",
                    "Minimal silver chain",
                    "Minimal gold chain",
                    "Black cord pendant",
                    "Double layered chains",
                    "Chain + dog tag pendant"
                ],
                value="Silver dog tag pendant",
                label="Boy accessory",
                visible=False,
            )
            generate_btn = gr.Button("Generate Try-On", variant="primary")
            clear_btn = gr.ClearButton(
                components=[input_image, girl_accessory, boy_accessory],
                value="Clear",
            )

        with gr.Column():
            output_image = gr.Image(label="Edited Result", type="pil")

    style_mode.change(
        fn=toggle_accessory_dropdowns,
        inputs=style_mode,
        outputs=[girl_accessory, boy_accessory],
    )

    generate_btn.click(
        fn=generate_try_on,
        inputs=[input_image, style_mode, girl_accessory, boy_accessory],
        outputs=output_image,
    )

    gr.Markdown(
        '''
### Notes
- This is a generative edit, so perfect pixel-level identity preservation is not guaranteed.
- Best results come from well-lit, front-facing or slightly angled upper-body photos.
- For stronger face preservation in production, the next step would be a neck-only mask or landmark-based overlay pipeline.
        '''
    )

print("Gradio app object created.")

"""## 4. Launch the app"""

demo.launch(debug=True)