# -*- coding: utf-8 -*-
"""dressme_ai_virtual_dress_tryon_lite_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11pmZnHI_UrG-ga08-ZyIVclxB737XiMg

# DressMe AI — Virtual Dress Try-On Lite

Upload:

1. A full-body / half-body photo of yourself
2. A dress product image, for example an Amazon dress screenshot or product image
3. A styling instruction, for example: `Show how this dress could look on me for a wedding guest look`

The notebook will:

- analyze the person image
- analyze the dress image
- generate a virtual try-on style preview
- produce fit/styling notes
- create a side-by-side visual output
- run as an interactive Gradio app

## Important note

This is a **visual try-on concept MVP**, not an exact sizing or fit engine. It can help visualize style compatibility, but it should not be treated as a true measurement-accurate fitting system.

## Model usage

- `gpt-4.1-mini` for image understanding and structured fashion analysis
- `gpt-image-1` for image editing / try-on-style preview

## 1. Setup

In Google Colab:

1. Open the left sidebar.
2. Click the 🔑 **Secrets** icon.
3. Add a secret named `OPENAI_API_KEY`.

Do not paste your API key directly into the notebook.
"""

!pip -q install openai gradio pillow pandas

import os
import io
import re
import gc
import json
import time
import base64
import html
import tempfile
from pathlib import Path

import pandas as pd
from PIL import Image, ImageDraw, ImageFont
from IPython.display import display, HTML

from openai import OpenAI
from openai import InternalServerError, APIConnectionError, RateLimitError, APIStatusError
from google.colab import userdata

OPENAI_API_KEY = userdata.get("OPENAI_API_KEY")

if not OPENAI_API_KEY:
    raise ValueError("Missing OPENAI_API_KEY. Add it in Colab Secrets.")

client = OpenAI(api_key=OPENAI_API_KEY)

print("Setup complete.")

"""## 2. Image helpers"""

def load_image(path_or_image):
    if isinstance(path_or_image, Image.Image):
        return path_or_image.convert("RGB")
    return Image.open(path_or_image).convert("RGB")


def resize_for_api(image: Image.Image, max_size: int = 1024) -> Image.Image:
    image = image.convert("RGB")
    image.thumbnail((max_size, max_size))
    return image


def pil_image_to_data_url(image: Image.Image, max_size: int = 768) -> str:
    image = resize_for_api(image, max_size=max_size)
    buffer = io.BytesIO()
    image.save(buffer, format="JPEG", quality=85)
    encoded = base64.b64encode(buffer.getvalue()).decode("utf-8")
    return f"data:image/jpeg;base64,{encoded}"


def save_temp_png(image: Image.Image, name: str) -> str:
    path = f"/content/{name}.png"
    image.convert("RGB").save(path, format="PNG")
    return path


def decode_image_response(response, output_path="/content/dressme_tryon_result.png"):
    """Handles either b64_json or URL-style image responses."""
    item = response.data[0]

    if getattr(item, "b64_json", None):
        image_bytes = base64.b64decode(item.b64_json)
        with open(output_path, "wb") as f:
            f.write(image_bytes)
        return output_path

    if getattr(item, "url", None):
        import requests
        r = requests.get(item.url, timeout=60)
        r.raise_for_status()
        with open(output_path, "wb") as f:
            f.write(r.content)
        return output_path

    raise ValueError("No image found in OpenAI image response.")

"""## 3. Analyze person + dress images

This does not generate the try-on image yet. It creates structured fashion context used for the edit prompt and styling notes.
"""

def analyze_person_and_dress(person_image: Image.Image, dress_image: Image.Image, user_instruction: str = "", max_retries: int = 3) -> dict:
    person_url = pil_image_to_data_url(person_image, max_size=768)
    dress_url = pil_image_to_data_url(dress_image, max_size=768)

    system_prompt = """
You are DressMe AI, a respectful fashion-tech virtual styling assistant.
You analyze a person photo and a garment/product photo for virtual try-on context.

Safety and quality rules:
- Focus on outfit, garment, styling, pose, lighting, and visual compatibility.
- Do not comment on body size, weight, attractiveness, ethnicity, age, disability, or other sensitive traits.
- Do not claim exact sizing or fit accuracy.
- If details are uncertain, say so.
- Return only valid JSON. No markdown.
"""

    user_prompt = f"""
User instruction:
{user_instruction}

Analyze the first image as the person photo and the second image as the dress/product photo.

Return JSON with exactly these keys:
- person_photo_summary
- dress_summary
- dress_type
- dress_colors
- dress_silhouette
- dress_material_guess
- neckline
- sleeve_length
- occasion_fit
- visual_compatibility_notes
- tryon_prompt
- styling_tips
- footwear_suggestions
- accessory_suggestions
- limitations

Requirements:
- tryon_prompt should be a precise image-editing prompt for generating a try-on preview.
- It should ask to preserve the person's face, pose, background, lighting, and identity while replacing visible clothing with the dress from the reference image.
- It should not claim exact garment fit.
- styling_tips, footwear_suggestions, accessory_suggestions, and limitations should be lists.
"""

    last_error = None

    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4.1-mini",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {
                        "role": "user",
                        "content": [
                            {"type": "text", "text": user_prompt},
                            {"type": "image_url", "image_url": {"url": person_url, "detail": "low"}},
                            {"type": "image_url", "image_url": {"url": dress_url, "detail": "low"}}
                        ]
                    }
                ],
                temperature=0.2,
                response_format={"type": "json_object"}
            )

            raw = response.choices[0].message.content.strip()
            raw = re.sub(r"^```json\s*", "", raw)
            raw = re.sub(r"^```\s*", "", raw)
            raw = re.sub(r"\s*```$", "", raw)
            return json.loads(raw)

        except (InternalServerError, APIConnectionError, RateLimitError, APIStatusError) as e:
            last_error = e
            print(f"OpenAI analysis error on attempt {attempt + 1}/{max_retries}: {e}")
            time.sleep(2 ** attempt)

        except json.JSONDecodeError as e:
            last_error = e
            print(f"JSON parse error on attempt {attempt + 1}/{max_retries}: {e}")
            time.sleep(2 ** attempt)

    return {
        "person_photo_summary": "Analysis failed.",
        "dress_summary": "Analysis failed.",
        "dress_type": "dress",
        "dress_colors": [],
        "dress_silhouette": "unknown",
        "dress_material_guess": "unknown",
        "neckline": "unknown",
        "sleeve_length": "unknown",
        "occasion_fit": "unknown",
        "visual_compatibility_notes": "Could not analyze because of an API error.",
        "tryon_prompt": f"Create a respectful virtual try-on concept image using the person photo and the dress reference image. Preserve the person's pose, face, background, and lighting. Visualize the dress on the person as a fashion styling preview. User instruction: {user_instruction}",
        "styling_tips": ["Try again with clearer images."],
        "footwear_suggestions": [],
        "accessory_suggestions": [],
        "limitations": [f"OpenAI analysis failed: {last_error}"]
    }

"""## 4. Generate virtual try-on preview

This uses OpenAI image editing with two input images:

1. person image
2. dress reference image

If image editing fails, the notebook will still return analysis and a side-by-side concept board.
"""

def generate_tryon_preview(person_image: Image.Image, dress_image: Image.Image, analysis: dict, user_instruction: str = "", max_retries: int = 2) -> str:
    person_small = resize_for_api(person_image, max_size=1024)
    dress_small = resize_for_api(dress_image, max_size=1024)

    person_path = save_temp_png(person_small, "dressme_person_input")
    dress_path = save_temp_png(dress_small, "dressme_dress_input")

    base_prompt = analysis.get("tryon_prompt", "")

    prompt = f"""
Create a realistic virtual try-on fashion preview.

Use image 1 as the person reference.
Use image 2 as the dress/garment reference.

Goal:
Visualize the person wearing the dress from the product image.

Important constraints:
- Preserve the person's face, identity, pose, body position, background, and lighting as much as possible.
- Preserve the dress color, neckline, sleeve style, silhouette, and visible design details as much as possible.
- Replace only the visible outfit/clothing area needed for the try-on.
- Keep the output tasteful, realistic, and fashion e-commerce appropriate.
- Do not sexualize the image.
- Do not change body shape.
- This is a visual styling preview, not an exact fit or size guarantee.

User instruction:
{user_instruction}

Fashion analysis context:
{json.dumps(analysis, indent=2)}

Editing prompt from analysis:
{base_prompt}
"""

    last_error = None

    for attempt in range(max_retries):
        try:
            with open(person_path, "rb") as person_file, open(dress_path, "rb") as dress_file:
                response = client.images.edit(
                    model="gpt-image-1",
                    image=[person_file, dress_file],
                    prompt=prompt,
                    size="1024x1024"
                )

            return decode_image_response(response, output_path="/content/dressme_tryon_result.png")

        except Exception as e:
            last_error = e
            print(f"Image edit error on attempt {attempt + 1}/{max_retries}: {e}")
            time.sleep(2 ** attempt)

    print("Try-on image generation failed. Returning side-by-side board instead.")
    return create_fallback_board(person_image, dress_image, analysis, output_path="/content/dressme_fallback_board.jpg", error=last_error)

"""## 5. Create side-by-side board and styling output"""

def wrap_text(text, max_chars=60):
    words = str(text).split()
    lines = []
    line = ""
    for word in words:
        candidate = (line + " " + word).strip()
        if len(candidate) <= max_chars:
            line = candidate
        else:
            if line:
                lines.append(line)
            line = word
    if line:
        lines.append(line)
    return lines


def fit_to_box(image, box_w, box_h):
    image = image.convert("RGB")
    image.thumbnail((box_w, box_h))
    canvas = Image.new("RGB", (box_w, box_h), "white")
    x = (box_w - image.width) // 2
    y = (box_h - image.height) // 2
    canvas.paste(image, (x, y))
    return canvas


def create_fallback_board(person_image, dress_image, analysis, output_path="/content/dressme_fallback_board.jpg", error=None):
    box_w, box_h = 430, 560
    panel_h = 360
    canvas = Image.new("RGB", (box_w * 2, box_h + panel_h), "white")

    p = fit_to_box(person_image, box_w, box_h)
    d = fit_to_box(dress_image, box_w, box_h)
    canvas.paste(p, (0, 0))
    canvas.paste(d, (box_w, 0))

    draw = ImageDraw.Draw(canvas)

    try:
        title_font = ImageFont.truetype("DejaVuSans-Bold.ttf", 28)
        header_font = ImageFont.truetype("DejaVuSans-Bold.ttf", 20)
        body_font = ImageFont.truetype("DejaVuSans.ttf", 17)
    except Exception:
        title_font = ImageFont.load_default()
        header_font = ImageFont.load_default()
        body_font = ImageFont.load_default()

    draw.text((20, 20), "Your Photo", fill="black", font=header_font)
    draw.text((box_w + 20, 20), "Dress Reference", fill="black", font=header_font)

    y = box_h + 24
    x = 28
    draw.text((x, y), "DressMe AI Try-On Concept", fill="black", font=title_font)
    y += 46

    summary = analysis.get("dress_summary", "")
    occasion = analysis.get("occasion_fit", "")
    notes = analysis.get("visual_compatibility_notes", "")
    limitations = analysis.get("limitations", [])

    text_blocks = [
        f"Dress: {summary}",
        f"Occasion fit: {occasion}",
        f"Compatibility: {notes}",
    ]

    if error:
        text_blocks.append(f"Preview generation fallback: {error}")

    if limitations:
        if isinstance(limitations, list):
            text_blocks.append("Limitations: " + "; ".join([str(x) for x in limitations[:2]]))
        else:
            text_blocks.append("Limitations: " + str(limitations))

    for block in text_blocks:
        for line in wrap_text(block, max_chars=90):
            draw.text((x, y), line, fill="black", font=body_font)
            y += 25
        y += 8

    canvas.save(output_path)
    return output_path


def create_final_board(person_image, dress_image, tryon_path, analysis, output_path="/content/dressme_final_board.jpg"):
    tryon_image = Image.open(tryon_path).convert("RGB")

    box_w, box_h = 360, 480
    panel_h = 360
    canvas = Image.new("RGB", (box_w * 3, box_h + panel_h), "white")

    images = [
        (person_image, "Your Photo"),
        (dress_image, "Dress Reference"),
        (tryon_image, "AI Try-On Preview")
    ]

    draw = ImageDraw.Draw(canvas)

    try:
        title_font = ImageFont.truetype("DejaVuSans-Bold.ttf", 28)
        header_font = ImageFont.truetype("DejaVuSans-Bold.ttf", 18)
        body_font = ImageFont.truetype("DejaVuSans.ttf", 16)
    except Exception:
        title_font = ImageFont.load_default()
        header_font = ImageFont.load_default()
        body_font = ImageFont.load_default()

    for i, (img, label) in enumerate(images):
        fitted = fit_to_box(img, box_w, box_h)
        canvas.paste(fitted, (i * box_w, 0))
        draw.text((i * box_w + 18, 18), label, fill="black", font=header_font)

    y = box_h + 22
    x = 28
    draw.text((x, y), "DressMe AI — Try-On Lite", fill="black", font=title_font)
    y += 44

    tips = analysis.get("styling_tips", [])
    footwear = analysis.get("footwear_suggestions", [])
    accessories = analysis.get("accessory_suggestions", [])
    limitations = analysis.get("limitations", [])

    blocks = []
    blocks.append("Dress: " + str(analysis.get("dress_summary", "")))
    blocks.append("Occasion: " + str(analysis.get("occasion_fit", "")))
    if tips:
        blocks.append("Styling tips: " + "; ".join([str(x) for x in tips[:3]]) if isinstance(tips, list) else str(tips))
    if footwear:
        blocks.append("Footwear: " + "; ".join([str(x) for x in footwear[:2]]) if isinstance(footwear, list) else str(footwear))
    if accessories:
        blocks.append("Accessories: " + "; ".join([str(x) for x in accessories[:2]]) if isinstance(accessories, list) else str(accessories))
    if limitations:
        blocks.append("Note: " + "; ".join([str(x) for x in limitations[:2]]) if isinstance(limitations, list) else str(limitations))

    for block in blocks:
        for line in wrap_text(block, max_chars=105):
            draw.text((x, y), line, fill="black", font=body_font)
            y += 23
        y += 6

    canvas.save(output_path)
    return output_path


def format_analysis_markdown(analysis):
    def bullets(items):
        if not items:
            return "- Not available"
        if isinstance(items, str):
            return f"- {items}"
        return "\n".join([f"- {x}" for x in items])

    return f"""
# DressMe AI Analysis

## Dress Summary
{analysis.get('dress_summary', '')}

## Dress Details
- Type: {analysis.get('dress_type', '')}
- Colors: {analysis.get('dress_colors', '')}
- Silhouette: {analysis.get('dress_silhouette', '')}
- Material guess: {analysis.get('dress_material_guess', '')}
- Neckline: {analysis.get('neckline', '')}
- Sleeve length: {analysis.get('sleeve_length', '')}

## Occasion Fit
{analysis.get('occasion_fit', '')}

## Visual Compatibility Notes
{analysis.get('visual_compatibility_notes', '')}

## Styling Tips
{bullets(analysis.get('styling_tips', []))}

## Footwear Suggestions
{bullets(analysis.get('footwear_suggestions', []))}

## Accessory Suggestions
{bullets(analysis.get('accessory_suggestions', []))}

## Limitations
{bullets(analysis.get('limitations', []))}
"""

"""## 6. One-shot test

Run this first before launching the app.
"""

from google.colab import files

print("Upload your person/full-body photo")
person_uploaded = files.upload()
person_path = next(iter(person_uploaded.keys()))
person_image = Image.open(person_path).convert("RGB")

print("Upload the dress/product image")
dress_uploaded = files.upload()
dress_path = next(iter(dress_uploaded.keys()))
dress_image = Image.open(dress_path).convert("RGB")

user_instruction = "Create a virtual try-on preview for a wedding guest look. Keep it realistic and tasteful."

display(person_image)
display(dress_image)

analysis = analyze_person_and_dress(person_image, dress_image, user_instruction)
print(json.dumps(analysis, indent=2))

tryon_path = generate_tryon_preview(person_image, dress_image, analysis, user_instruction)
final_board = create_final_board(person_image, dress_image, tryon_path, analysis)

display(Image.open(tryon_path))
display(Image.open(final_board))
display(HTML(format_analysis_markdown(analysis).replace("\n", "<br>")))

print("Try-on preview:", tryon_path)
print("Final board:", final_board)

"""## 7. Download result"""

from google.colab import files
files.download("/content/dressme_final_board.jpg")

"""## 8. Interactive Gradio app

This uses `type="filepath"` for more stable uploads in Colab.
"""

import gradio as gr

try:
    gr.close_all()
except Exception:
    pass

gc.collect()


def run_dressme(person_path, dress_path, user_instruction):
    if person_path is None or dress_path is None:
        return None, None, "Please upload both a person photo and a dress image.", pd.DataFrame()

    person_image = Image.open(person_path).convert("RGB")
    dress_image = Image.open(dress_path).convert("RGB")

    if not user_instruction or not user_instruction.strip():
        user_instruction = "Create a realistic virtual try-on preview and styling advice."

    analysis = analyze_person_and_dress(person_image, dress_image, user_instruction)
    tryon_path = generate_tryon_preview(person_image, dress_image, analysis, user_instruction)
    final_board = create_final_board(person_image, dress_image, tryon_path, analysis)

    markdown = format_analysis_markdown(analysis)

    return tryon_path, final_board, markdown, pd.DataFrame([analysis])


with gr.Blocks(title="DressMe AI — Virtual Dress Try-On Lite") as demo:
    gr.Markdown(
        "# DressMe AI — Virtual Dress Try-On Lite\n\n"
        "Upload your photo and a dress/product image. The app creates a visual try-on style preview and styling notes.\n\n"
        "Note: This is a concept preview, not an exact sizing or fit engine."
    )

    with gr.Row():
        with gr.Column(scale=1):
            person_input = gr.Image(type="filepath", label="Upload Your Photo", height=360)
            dress_input = gr.Image(type="filepath", label="Upload Dress/Product Image", height=360)
            instruction = gr.Textbox(
                label="Styling instruction",
                value="Create a virtual try-on preview for a wedding guest look. Keep it realistic and tasteful.",
                lines=3
            )
            run_button = gr.Button("Generate Try-On Preview", variant="primary")

        with gr.Column(scale=1):
            tryon_output = gr.Image(type="filepath", label="AI Try-On Preview")
            board_output = gr.Image(type="filepath", label="Shareable Result Board")

    analysis_output = gr.Markdown(label="Styling Analysis")
    raw_output = gr.Dataframe(label="Raw Structured Output", wrap=True)

    run_button.click(
        fn=run_dressme,
        inputs=[person_input, dress_input, instruction],
        outputs=[tryon_output, board_output, analysis_output, raw_output]
    )


demo.queue(default_concurrency_limit=1).launch(
    debug=False,
    share=True,
    prevent_thread_lock=True,
    show_error=True
)

"""## 9. MVP extensions

To make this more impressive:

1. Add occasion presets: wedding guest, date night, office, festival, party.
2. Add accessory generation: shoes, bag, jewelry suggestions.
3. Add retailer search: use the dress analysis to find matching shoes or bags.
4. Add share card templates for LinkedIn/Instagram.
5. Add multiple dress comparison: upload 3 dresses and rank which one suits the occasion best.
6. Add Indian ethnic wear mode: saree, lehenga, kurta, anarkali, Indo-western.
"""