# -*- coding: utf-8 -*-
"""visual_shoe_search_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zCDu68KMUfljNurkiScRRTOldAr7A0V4

# Visual Shoe Search

Upload a shoe image and ask for similar shoes online.

This notebook uses:
- OpenAI Vision to understand the uploaded shoe image
- DDGS / DuckDuckGo-style search to find similar shoes online
- Gradio for an interactive UI
"""

!pip -q install openai gradio pillow pandas ddgs

import os
import re
import io
import json
import time
import base64
import html
import pandas as pd
from PIL import Image
from IPython.display import HTML, display

from openai import OpenAI
from openai import InternalServerError, APIConnectionError, RateLimitError, APIStatusError
from google.colab import userdata
from ddgs import DDGS

OPENAI_API_KEY = userdata.get("OPENAI_API_KEY")

if not OPENAI_API_KEY:
    raise ValueError("Missing OPENAI_API_KEY. Add it in Colab Secrets.")

client = OpenAI(api_key=OPENAI_API_KEY)

print("Setup complete. OPENAI_API_KEY loaded from Colab Secrets.")

"""## 2. Image helper"""

def pil_image_to_data_url(image: Image.Image, max_size: int = 768) -> str:
    image = image.convert("RGB")
    image.thumbnail((max_size, max_size))

    buffer = io.BytesIO()
    image.save(buffer, format="JPEG", quality=85)
    encoded = base64.b64encode(buffer.getvalue()).decode("utf-8")

    return f"data:image/jpeg;base64,{encoded}"

"""## 3. Extract shoe attributes with retry + fallback"""

def extract_shoe_attributes(
    image: Image.Image,
    user_instruction: str = "",
    max_retries: int = 3
) -> dict:
    data_url = pil_image_to_data_url(image, max_size=768)

    system_prompt = """
You are a fashion-tech visual shopping assistant.
Analyze a shoe image and create useful shopping-search attributes.
Do not identify a brand unless the logo or text is clearly visible.
Return only valid JSON. No markdown.
"""

    user_prompt = f"""
Analyze this uploaded shoe image.

User shopping instruction:
{user_instruction}

Return JSON with these keys:
- product_type
- primary_colors
- secondary_colors
- silhouette
- material_guess
- sole_type
- closure_type
- style_keywords
- occasion
- gender_guess
- visible_brand_or_logo
- confidence_notes
- search_query
- image_search_query
- negative_keywords

Rules:
- search_query should be useful for web shopping search.
- image_search_query should be useful for image search.
- Include user's constraints such as budget, country, gender, or brand preference if provided.
- For India queries, include India, online, buy, and INR-style terms when useful.
- Do not overclaim material or brand.
- Keep the search query short and specific.
"""

    last_error = None

    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4.1-mini",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {
                        "role": "user",
                        "content": [
                            {"type": "text", "text": user_prompt},
                            {
                                "type": "image_url",
                                "image_url": {
                                    "url": data_url,
                                    "detail": "low"
                                }
                            }
                        ]
                    }
                ],
                temperature=0.2,
                response_format={"type": "json_object"}
            )

            raw = response.choices[0].message.content.strip()
            raw = re.sub(r"^```json\s*", "", raw)
            raw = re.sub(r"^```\s*", "", raw)
            raw = re.sub(r"\s*```$", "", raw)
            return json.loads(raw)

        except (InternalServerError, APIConnectionError, RateLimitError, APIStatusError) as e:
            last_error = e
            print(f"OpenAI API error on attempt {attempt + 1}/{max_retries}: {e}")
            time.sleep(2 ** attempt)

        except json.JSONDecodeError as e:
            last_error = e
            print(f"JSON parse error on attempt {attempt + 1}/{max_retries}: {e}")
            time.sleep(2 ** attempt)

    print("Vision analysis failed after retries. Using fallback query.")

    fallback_instruction = user_instruction.strip() or "similar shoes online"

    return {
        "product_type": "shoes",
        "primary_colors": [],
        "secondary_colors": [],
        "silhouette": "unknown",
        "material_guess": [],
        "sole_type": "unknown",
        "closure_type": "unknown",
        "style_keywords": ["similar shoes"],
        "occasion": "unknown",
        "gender_guess": "unknown",
        "visible_brand_or_logo": "unknown",
        "confidence_notes": f"OpenAI vision call failed after retries: {last_error}",
        "search_query": f"buy similar shoes online {fallback_instruction}",
        "image_search_query": f"similar shoes {fallback_instruction}",
        "negative_keywords": []
    }

"""\## 4. Search the internet"""

def ddg_text_search(query: str, max_results: int = 10, region: str = "in-en") -> list:
    results = []
    try:
        with DDGS() as ddgs:
            for item in ddgs.text(
                query,
                region=region,
                safesearch="moderate",
                max_results=max_results
            ):
                href = item.get("href")
                source = None
                if href:
                    try:
                        source = href.split("/")[2]
                    except Exception:
                        source = href

                results.append({
                    "result_type": "web",
                    "title": item.get("title"),
                    "snippet": item.get("body"),
                    "link": href,
                    "source": source,
                    "thumbnail": None,
                })
    except Exception as e:
        print(f"DDG text search failed: {e}")

    return results


def ddg_image_search(query: str, max_results: int = 12, region: str = "in-en") -> list:
    results = []
    try:
        with DDGS() as ddgs:
            for item in ddgs.images(
                query,
                region=region,
                safesearch="moderate",
                max_results=max_results
            ):
                results.append({
                    "result_type": "image",
                    "title": item.get("title"),
                    "snippet": item.get("source"),
                    "link": item.get("url"),
                    "source": item.get("source"),
                    "thumbnail": item.get("thumbnail") or item.get("image"),
                })
    except Exception as e:
        print(f"DDG image search failed: {e}")

    return results


def search_similar_shoes(
    attributes: dict,
    user_instruction: str,
    max_results: int = 12,
    region: str = "in-en"
) -> list:
    web_query = attributes.get("search_query") or "similar shoes online"
    image_query = attributes.get("image_search_query") or web_query

    if "buy" not in web_query.lower() and "online" not in web_query.lower():
        web_query = f"buy {web_query} online"

    image_results = ddg_image_search(image_query, max_results=max_results, region=region)
    web_results = ddg_text_search(web_query, max_results=max_results, region=region)

    merged = image_results + web_results

    seen = set()
    deduped = []
    for item in merged:
        key = item.get("link") or item.get("title")
        if key and key not in seen:
            seen.add(key)
            deduped.append(item)

    return deduped[:max_results]

"""## 5. Rank results with ChatGPT"""

def rank_results_with_llm(attributes: dict, results: list, user_instruction: str = "") -> str:
    if not results:
        return "No search results found to rank."

    compact_results = []
    for i, item in enumerate(results, start=1):
        compact_results.append({
            "rank": i,
            "title": item.get("title"),
            "source": item.get("source"),
            "snippet": item.get("snippet"),
            "link": item.get("link"),
            "result_type": item.get("result_type"),
        })

    prompt = f"""
You are a fashion-tech shopping assistant.

Uploaded shoe attributes:
{json.dumps(attributes, indent=2)}

User request:
{user_instruction}

Search results:
{json.dumps(compact_results, indent=2)}

Tasks:
1. Pick the top 3 most visually or semantically similar results.
2. Explain briefly why each is a good match.
3. Mention if a result is approximate.
4. Remind the user to manually verify product details before purchase.

Keep the response concise.
"""

    try:
        response = client.chat.completions.create(
            model="gpt-4.1-mini",
            messages=[
                {"role": "system", "content": "You are a concise fashion shopping result ranking assistant."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.2
        )
        return response.choices[0].message.content

    except Exception as e:
        return f"Ranking failed, but search results are still shown. Error: {e}"

"""## 6. Visual product cards"""

def safe_text(value):
    return html.escape(str(value)) if value is not None else ""


def make_cards_html(results):
    if not results:
        return "<h3>No results found.</h3>"

    card_html = """
    <div style="
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(230px, 1fr));
        gap: 16px;
        font-family: Arial, sans-serif;
    ">
    """

    for item in results:
        img = safe_text(item.get("thumbnail") or "")
        title_text = safe_text(item.get("title") or "Untitled result")
        source = safe_text(item.get("source") or "Unknown source")
        snippet = safe_text((item.get("snippet") or "")[:150])
        link = safe_text(item.get("link") or "#")
        result_type = safe_text(item.get("result_type") or "result")

        if img:
            image_html = f'<img src="{img}" style="max-height: 170px; max-width: 100%; object-fit: contain;" />'
        else:
            image_html = '<span style="color:#999;">No image</span>'

        card_html += f"""
        <div style="
            border: 1px solid #e5e5e5;
            border-radius: 14px;
            padding: 12px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
            background: white;
        ">
            <div style="height: 180px; display:flex; align-items:center; justify-content:center; background:#fafafa; border-radius:10px;">
                {image_html}
            </div>
            <p style="font-size: 12px; color: #777; text-transform: uppercase;">{result_type}</p>
            <h3 style="font-size: 15px; line-height: 1.3; min-height: 56px;">{title_text}</h3>
            <p style="color: #555; margin: 6px 0;">{source}</p>
            <p style="color: #777; font-size: 13px; line-height: 1.3; min-height: 48px;">{snippet}</p>
            <a href="{link}" target="_blank" style="
                display: inline-block;
                margin-top: 8px;
                padding: 8px 10px;
                border-radius: 8px;
                text-decoration: none;
                background: #111;
                color: white;
            ">Open result</a>
        </div>
        """

    card_html += "</div>"
    return card_html

"""## 7. One-shot test"""

from google.colab import files

uploaded = files.upload()

uploaded_image_path = next(iter(uploaded.keys()))
image = Image.open(uploaded_image_path).convert("RGB")

user_instruction = "Find similar shoes online in India under ₹5000"

display(image)

attributes = extract_shoe_attributes(image, user_instruction)
print("Detected attributes:")
print(json.dumps(attributes, indent=2))

results = search_similar_shoes(
    attributes=attributes,
    user_instruction=user_instruction,
    max_results=12,
    region="in-en"
)

ranking_summary = rank_results_with_llm(attributes, results, user_instruction)
print("\nLLM ranking summary:")
print(ranking_summary)

display(HTML(make_cards_html(results)))

"""## 8. Interactive Gradio app"""

import gradio as gr
import gc
import time

try:
    gr.close_all()
except Exception as e:
    print("gr.close_all warning:", e)

gc.collect()
time.sleep(2)

print("Closed old Gradio apps.")

import gradio as gr

def run_visual_shopping_search(image, user_instruction, region, num_results):
    if image is None:
        return None, "Please upload a shoe image.", pd.DataFrame(), ""

    if not user_instruction or not user_instruction.strip():
        user_instruction = "Find similar shoes online"

    attributes = extract_shoe_attributes(image, user_instruction)

    results = search_similar_shoes(
        attributes=attributes,
        user_instruction=user_instruction,
        max_results=int(num_results),
        region=region
    )

    ranking = rank_results_with_llm(attributes, results, user_instruction)

    rows = []
    for i, item in enumerate(results, start=1):
        rows.append({
            "Rank": i,
            "Title": item.get("title"),
            "Source": item.get("source"),
            "Snippet": item.get("snippet"),
            "Type": item.get("result_type"),
            "Link": item.get("link"),
            "Thumbnail": item.get("thumbnail"),
        })

    df_results = pd.DataFrame(rows)

    query = attributes.get("search_query", "")

    markdown = (
        "## Detected Shoe Attributes\n\n"
        "```json\n"
        + json.dumps(attributes, indent=2)
        + "\n```\n\n"
        + "## Generated Search Query\n\n"
        + f"`{query}`\n\n"
        + "## LLM Ranking Summary\n\n"
        + ranking
    )

    return image, markdown, df_results, make_cards_html(results)


with gr.Blocks(title="Visual Shoe Search") as demo:
    gr.Markdown(
        "# Visual Shoe Search\n\n"
        "Upload a shoe photo to find similar shoes. "
        ""
    )

    with gr.Row():
        with gr.Column(scale=1):
            input_image = gr.Image(type="pil", label="Upload Shoe Image")
            user_instruction = gr.Textbox(
                label="What do you want to find?",
                value="Find similar shoes under ₹5000 in India",
                lines=2
            )
            region = gr.Dropdown(
                label="Search Region",
                choices=["in-en", "us-en", "uk-en", "ca-en", "au-en"],
                value="in-en"
            )
            num_results = gr.Slider(
                label="Number of results",
                minimum=4,
                maximum=24,
                value=12,
                step=1
            )
            run_button = gr.Button("Find Similar Shoes", variant="primary")

        with gr.Column(scale=1):
            image_preview = gr.Image(type="pil", label="Uploaded Image Preview")
            analysis_markdown = gr.Markdown(label="Analysis")

    results_table = gr.Dataframe(label="Search Results Table", wrap=True)
    product_cards = gr.HTML(label="Visual Result Cards")

    run_button.click(
        fn=run_visual_shopping_search,
        inputs=[input_image, user_instruction, region, num_results],
        outputs=[image_preview, analysis_markdown, results_table, product_cards]
    )

#demo.launch(debug=True, share=True)
demo.queue(default_concurrency_limit=1).launch(
    debug=False,
    share=True,
    prevent_thread_lock=True,
    show_error=True
)

"""## 9. Production notes

This notebook is good for a prototype/demo.

For a real fashion-tech product, use this safer architecture:

```text
Frontend
  ↓
Your backend API
  ↓
OpenAI Vision + your catalog / official retailer APIs
  ↓
Sanitized product cards
```

Best production data sources:
1. Your own catalog with CLIP or embedding search.
2. Official retailer APIs.
3. Affiliate product feeds.
4. A backend-controlled search provider.

Avoid exposing private search/API keys in frontend code.
"""